apiVersion: v1
kind: Service
metadata:
  name: n8n-service
  namespace: n8n
  labels:
    service: n8n
  annotations:
    cloud.google.com/backend-config: '{"default": "n8n-backendconfig"}'
    # cloud.google.com/backend-config: '{"ports": {"5678":"my-backendconfig"}}'
    # cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  ports:
    - name: "5678"
      port: 5678
      targetPort: 5678
      protocol: TCP
  selector:
    service: n8n
