apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: n8n-backendconfig
  namespace: n8n
spec:
  timeoutSec: 40
  connectionDraining:
    drainingTimeoutSec: 60
  healthCheck:
    checkIntervalSec: 20
    timeoutSec: 20
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: "HTTP"
    requestPath: /healthz
    port: 5678
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: n8n-iap-secret
