apiVersion: v1
kind: Secret
metadata:
  namespace: data
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_DB: n8n
  POSTGRES_USER: ADMIN_USERNAME
  POSTGRES_PASSWORD: ADMIN_PASSWORD
  POSTGRES_NON_ROOT_USER: APPUSER_USERNAME
  POSTGRES_NON_ROOT_PASSWORD: APPUSER_PASSWORD
