apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: n8n-frontendconfig
  namespace: n8n
spec:
  sslPolicy: modern-ssl-policy
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
